#!/bin/bash
TESTDIR="tests"
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'
if [ ! -d "./tmp" ]; then
    mkdir tmp
fi
for filename in `ls $TESTDIR/`; do
    echo "Running Test $filename"
    ./kpython $TESTDIR/$filename > tmp/$filename.kpython.out 2>/dev/null
    python3 $TESTDIR/$filename > tmp/$filename.python.out 2>/dev/null
    if diff tmp/$filename.kpython.out tmp/$filename.python.out >/dev/null ; then
        echo -e "${GREEN}Test Passed${NC}"
    else
        echo -e "${RED}Test Failed${NC}"
    fi
done
